# Car sales price predection

In [2]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Preprocesser
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# process (Train and structure)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Evolution
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

# warning
import warnings
warnings.filterwarnings("ignore")


C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/resource_handle.proto. Please update th

Read the dataset

In [3]:
df = pd.read_csv(r"C:\Users\HP\OneDrive\Documents\SENAPATI SIR FSDS NOTE\NOVEMBER MONTH DS NOTE\6th, 7th- ANN THEORY, Installation\car_purchasing.csv", encoding='latin1')
df.head()

customer name                                    customer e-mail  \
0    Martina Avila  cubilia.Curae.Phasellus@quisaccumsanconvallis.edu   
1    Harlan Barnes                                eu.dolor@diam.co.uk   
2  Naomi Rodriquez  vulputate.mauris.sagittis@ametconsectetueradip...   
3  Jade Cunningham                            malesuada@dignissim.com   
4     Cedric Leach     felis.ullamcorper.viverra@egetmollislectus.net   

        country  gender        age  annual Salary  credit card debt  \
0      Bulgaria       0  41.851720    62812.09301      11609.380910   
1        Belize       0  40.870623    66646.89292       9572.957136   
2       Algeria       1  43.152897    53798.55112      11160.355060   
3  Cook Islands       1  58.271369    79370.03798      14426.164850   
4        Brazil       1  57.313749    59729.15130       5358.712177   

     net worth  car purchase amount  
0  238961.2505          35321.45877  
1  530973.9078          45115.52566  
2  638467.1773          42925.70921  
3  548599.0524          67422.36313  
4  560304.0671          55915.46248

In [4]:
df.shape

(500, 9)

In [5]:
df.sample()
# Randomly picks 1 row from the dataset and displays it

customer name customer e-mail    country  gender        age  \
68  Nissim Acosta     enim@at.net  Mauritius       1  57.347216   

    annual Salary  credit card debt    net worth  car purchase amount  
68    48716.67271       10886.91711  662382.6623          52707.96816

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   customer name        500 non-null    object 
 1   customer e-mail      500 non-null    object 
 2   country              500 non-null    object 
 3   gender               500 non-null    int64  
 4   age                  500 non-null    float64
 5   annual Salary        500 non-null    float64
 6   credit card debt     500 non-null    float64
 7   net worth            500 non-null    float64
 8   car purchase amount  500 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 35.3+ KB


In [7]:
df.isnull().sum()

customer name          0
customer e-mail        0
country                0
gender                 0
age                    0
annual Salary          0
credit card debt       0
net worth              0
car purchase amount    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.columns

Index(['customer name', 'customer e-mail', 'country', 'gender', 'age',
       'annual Salary', 'credit card debt', 'net worth',
       'car purchase amount'],
      dtype='object')

In [10]:
df.head()

customer name                                    customer e-mail  \
0    Martina Avila  cubilia.Curae.Phasellus@quisaccumsanconvallis.edu   
1    Harlan Barnes                                eu.dolor@diam.co.uk   
2  Naomi Rodriquez  vulputate.mauris.sagittis@ametconsectetueradip...   
3  Jade Cunningham                            malesuada@dignissim.com   
4     Cedric Leach     felis.ullamcorper.viverra@egetmollislectus.net   

        country  gender        age  annual Salary  credit card debt  \
0      Bulgaria       0  41.851720    62812.09301      11609.380910   
1        Belize       0  40.870623    66646.89292       9572.957136   
2       Algeria       1  43.152897    53798.55112      11160.355060   
3  Cook Islands       1  58.271369    79370.03798      14426.164850   
4        Brazil       1  57.313749    59729.15130       5358.712177   

     net worth  car purchase amount  
0  238961.2505          35321.45877  
1  530973.9078          45115.52566  
2  638467.1773          42925.70921  
3  548599.0524          67422.36313  
4  560304.0671          55915.46248

In [11]:
df.drop(columns=['customer name','customer e-mail','country','gender'],inplace= True)

In [12]:
df.head()

age  annual Salary  credit card debt    net worth  \
0  41.851720    62812.09301      11609.380910  238961.2505   
1  40.870623    66646.89292       9572.957136  530973.9078   
2  43.152897    53798.55112      11160.355060  638467.1773   
3  58.271369    79370.03798      14426.164850  548599.0524   
4  57.313749    59729.15130       5358.712177  560304.0671   

   car purchase amount  
0          35321.45877  
1          45115.52566  
2          42925.70921  
3          67422.36313  
4          55915.46248

In [15]:
# split the dataset to dependent and independent variables
x = df.drop('car purchase amount',axis = 1)
y = df['car purchase amount']

In [17]:
x.head()

age  annual Salary  credit card debt    net worth
0  41.851720    62812.09301      11609.380910  238961.2505
1  40.870623    66646.89292       9572.957136  530973.9078
2  43.152897    53798.55112      11160.355060  638467.1773
3  58.271369    79370.03798      14426.164850  548599.0524
4  57.313749    59729.15130       5358.712177  560304.0671

In [18]:
y.head()

0    35321.45877
1    45115.52566
2    42925.70921
3    67422.36313
4    55915.46248
Name: car purchase amount, dtype: float64

Preprocessing

In [19]:
scaler = MinMaxScaler()
x = scaler.fit_transform(x)
y = scaler.fit_transform(y.values.reshape(-1,1))

In [22]:
print(x)

[[0.4370344  0.53515116 0.57836085 0.22342985]
 [0.41741247 0.58308616 0.476028   0.52140195]
 [0.46305795 0.42248189 0.55579674 0.63108896]
 ...
 [0.67886994 0.61110973 0.52822145 0.75972584]
 [0.78321017 0.37264988 0.69914746 0.3243129 ]
 [0.53462305 0.51713347 0.46690159 0.45198622]]


In [23]:
print(y)

[[0.37072477]
 [0.50866938]
 [0.47782689]
 [0.82285018]
 [0.66078116]
 [0.67059152]
 [0.28064374]
 [0.54133778]
 [0.54948752]
 [0.4111198 ]
 [0.70486638]
 [0.46885649]
 [0.27746526]
 [0.56702642]
 [0.57056385]
 [0.61996151]
 [0.46217916]
 [0.49157341]
 [0.50188722]
 [0.64545808]
 [0.59339372]
 [0.48453965]
 [0.53860366]
 [0.53007738]
 [0.50814651]
 [0.49841668]
 [0.3966416 ]
 [0.56467566]
 [0.6950749 ]
 [0.49287831]
 [0.12090943]
 [0.50211776]
 [0.80794216]
 [0.62661214]
 [0.43394857]
 [0.60017103]
 [0.42223485]
 [0.01538345]
 [0.37927499]
 [0.64539707]
 [0.51838974]
 [0.45869677]
 [0.26804521]
 [0.2650104 ]
 [0.84054134]
 [0.84401542]
 [0.35515157]
 [0.406246  ]
 [0.40680623]
 [0.55963883]
 [0.2561583 ]
 [0.77096325]
 [0.55305289]
 [0.5264948 ]
 [0.3236476 ]
 [0.55070832]
 [0.54057623]
 [0.45669016]
 [0.41053254]
 [0.33433524]
 [0.39926954]
 [0.5420261 ]
 [0.57366948]
 [0.43793831]
 [0.46897896]
 [0.61908354]
 [0.55076214]
 [0.48846357]
 [0.61560519]
 [0.56891394]
 [0.30761974]
 [0.56

In [24]:
#split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [25]:
print(f'the shape of x_train: {x_train.shape}')
print(f'the shape of x_test: {x_test.shape}')
print(f'the shape of y_train: {y_train.shape}')
print(f'the shape of y_test: {y_test.shape}')

the shape of x_train: (400, 4)
the shape of x_test: (100, 4)
the shape of y_train: (400, 1)
the shape of y_test: (100, 1)


Structure

In [26]:
model = Sequential()
model.add(Dense(10,activation='relu',input_dim = 4))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='linear'))

model.compile(optimizer = 'adam',loss = 'mse')
model.summary()



Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 171 (684.00 B)

 Trainable params: 171 (684.00 B)

 Non-trainable params: 0 (0.00 B)





model = Sequential()


* Sequential() means you are creating a **linear stack of layers** — each layer’s output becomes the next layer’s input.
* It’s the simplest type of neural network model in Keras.

---

###  2️⃣ Add Layers

#### (a) Input + First Hidden Layer

```python
model.add(Dense(10, activation='relu', input_dim=4))
```

* `Dense` → A **fully connected** layer (each neuron connects to all neurons in the previous layer).
* `10` → Number of neurons in this layer.
* `activation='relu'` → Uses the **ReLU (Rectified Linear Unit)** activation function:
  [
  f(x) = \max(0, x)
  ]
  It helps the model learn non-linear patterns.
* `input_dim=4` → The input data has **4 features (columns)** — so the model expects each input sample to have 4 values.

✅ So this is your **input + first hidden layer**.

---

#### (b) Second Hidden Layer

```python
model.add(Dense(10, activation='relu'))
```

* Another fully connected layer with **10 neurons**.
* Again uses **ReLU** to introduce non-linearity.
* Learns more complex relationships between input features.

✅ This is your **second hidden layer**.

---

#### (c) Output Layer

```python
model.add(Dense(1, activation='linear'))
```

* This layer has **1 neuron** → suitable for **regression problems** (predicting a continuous number like car purchase amount 💰).
* `activation='linear'` → No transformation (the neuron just outputs the weighted sum).
  So, it can predict any real value.

✅ This is your **output layer**.

---

### ⚙️ 3️⃣ Compile the Model

```python
model.compile(optimizer='adam', loss='mse')
```

* **`optimizer='adam'`** → Adam optimizer adjusts learning rate automatically; efficient for most problems.
* **`loss='mse'`** → Mean Squared Error; used in regression to measure how far predictions are from real values.

✅ This tells Keras how the model should **learn**.

---

### 📋 4️⃣ Model Summary

```python
model.summary()
```

* Prints a **table of layers**, showing:

  * Layer type
  * Output shape
  * Number of parameters (weights and biases)


```

---

### 🧾 Summary Table

| Part          | Code                            | Purpose                          |
| ------------- | ------------------------------- | -------------------------------- |
| Model Type    | `Sequential()`                  | Linear stack of layers           |
| Hidden Layers | `Dense(10, activation='relu')`  | Extract patterns from input data |
| Output Layer  | `Dense(1, activation='linear')` | Predict continuous value         |
| Compile       | `optimizer='adam', loss='mse'`  | Define how model learns          |
| Summary       | `model.summary()`               | Show model architecture          |

---



# Model Traning

In [27]:
history = model.fit(x_train,y_train,epochs=10,validation_split=0.2)

Epoch 1/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0628 - val_loss: 0.0351
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0262 - val_loss: 0.0225
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0216 - val_loss: 0.0215
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0193 - val_loss: 0.0180
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0162 - val_loss: 0.0155
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0141 - val_loss: 0.0136
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0123 - val_loss: 0.0118
Epoch 8/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0106 - val_loss: 0.0102
Epoch 9/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0089 - val_loss: 0.0085
Epoch 10/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0073 - val_loss: 0.0071


In [32]:
y_pred = model.predict(x_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1   ))

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[0.         0.4219045 ]
 [1.         0.4845291 ]
 [0.         0.28757249]
 [1.         0.60775236]
 [1.         0.41187412]
 [1.         0.61996151]
 [1.         0.72573208]
 [1.         0.7118085 ]
 [0.         0.40442699]
 [0.         0.31409216]
 [0.         0.53305254]
 [1.         0.67567861]
 [0.         0.63371047]
 [1.         0.8715253 ]
 [0.         0.26605566]
 [0.         0.3172683 ]
 [1.         0.54900684]
 [1.         0.69953618]
 [1.         0.46999496]
 [0.         0.01538345]
 [1.         0.55660425]
 [0.         0.39694511]
 [0.         0.5257114 ]
 [0.         0.26178477]
 [1.         0.84401542]
 [1.         0.49152498]
 [0.         0.48453965]
 [1.         0.53113416]
 [1.         0.74075381]
 [1.         0.69345654]
 [1.         0.55657526]
 [1.         0.47313925]
 [0.         0.64444254]
 [1.         0.47569515]
 [1.         0.76168793]
 [1.         0.71996731]
 [0.         0.37628608]
 [1.         0.71808681]
 [0.        

y_pred = (y_pred > 0.5)

This converts probabilities into binary values (True/False or 1/0).

The threshold 0.5 means:

If prediction > 0.5 → class = 1 (True)

If prediction ≤ 0.5 → class = 0 (False)

✅ So now y_pred becomes a list of predicted classes instead of probabilities.

In [34]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R² Score:", r2)


Mean Squared Error: 0.17450394597322214
Mean Absolute Error: 0.40058939762253537
R² Score: -6.303632110664632


Evolution

In [30]:
r2 = r2_score(y_test,y_pred)
print(f'R2 Score: {r2}')

R2 Score: 0.7013730946792877
